# Generated by Django 5.0.4 on 2024-05-15 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CattleBreed',
            fields=[
                ('cattle_breed_id', models.AutoField(primary_key=True, serialize=False)),
                ('cattle_breed_type', models.CharField(max_length=100, null=True)),
                ('cattle_breed_description', models.CharField(max_length=200, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'cattle_breed',
            },
        ),
        migrations.CreateModel(
            name='CattleStatus',
            fields=[
                ('cattle_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('cattle_status', models.CharField(max_length=100, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'cattle_status',
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_type', models.CharField(max_length=255, null=True)),
                ('contact_type_desc', models.CharField(max_length=255, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'contact_type',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='FarmEntity',
            fields=[
                ('farm_entity_id', models.AutoField(primary_key=True, serialize=False)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'farm_entity',
            },
        ),
        migrations.CreateModel(
            name='FeedFormulation',
            fields=[
                ('feed_formulation_id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_formulation_description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'feed_formulation',
            },
        ),
        migrations.CreateModel(
            name='FeedTimeCategory',
            fields=[
                ('feed_time_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_time_category', models.CharField(max_length=200, null=True)),
                ('start_time', models.CharField(max_length=45, null=True)),
                ('end_time', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'feed_time_category',
            },
        ),
        migrations.CreateModel(
            name='GuaranteeType',
            fields=[
                ('guarantee_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('guarantee_type', models.CharField(max_length=100, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'guarantee_type',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=45)),
                ('job_min_salary', models.FloatField(null=True)),
                ('job_max_salary', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_date', models.DateField(null=True)),
                ('request_approved', models.CharField(max_length=10, null=True)),
                ('request_approved_date', models.DateTimeField(null=True)),
                ('purchase_approved', models.CharField(max_length=10, null=True)),
                ('purchase_approved_date', models.DateTimeField(null=True)),
                ('inventory_approved', models.CharField(max_length=10, null=True)),
                ('inventory_approved_date', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='PersonTitle',
            fields=[
                ('person_title_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_title', models.CharField(max_length=45, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'person_title',
            },
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('person_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_type', models.CharField(max_length=100, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'person_type',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='SaleType',
            fields=[
                ('sale_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_type', models.CharField(max_length=100, null=True)),
                ('modified_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'sale_type',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_name', models.CharField(max_length=45, null=True)),
                ('shift_start_time', models.DateTimeField(null=True)),
                ('shift_end_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'shift',
            },
        ),
        migrations.CreateModel(
            name='SupplierType',
            fields=[
                ('supplier_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_type', models.CharField(max_length=100, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'supplier_type',
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('vaccine_id', models.AutoField(primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=45, null=True)),
                ('vaccine_benefit', models.CharField(max_length=2555, null=True)),
                ('vaccine_recommended_time', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'vaccine',
            },
        ),
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('cattle_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cattle_date_of_birth', models.DateTimeField(null=True)),
                ('cattle_name', models.CharField(max_length=50, null=True)),
                ('cattle_gender', models.CharField(max_length=15, null=True)),
                ('estimated_price', models.FloatField(null=True)),
                ('cattle_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cattlebreed')),
                ('cattle_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cattlestatus')),
            ],
            options={
                'db_table': 'cattle',
            },
        ),
        migrations.CreateModel(
            name='CattlePhoto',
            fields=[
                ('cattle_photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('cattle_photo_url', models.CharField(max_length=200, null=True)),
                ('cattle_photo_description', models.CharField(max_length=200, null=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cattle')),
            ],
            options={
                'db_table': 'cattle_photo',
            },
        ),
        migrations.CreateModel(
            name='CattlePregnancy',
            fields=[
                ('cattle_pregnancy_id', models.AutoField(primary_key=True, serialize=False)),
                ('cattle_pregnancy_type', models.CharField(max_length=45, null=True)),
                ('cattle_pregnancy_date', models.DateField()),
                ('cattle_expected_delivery_date', models.DateField(null=True)),
                ('cattle_pregnancy_status', models.CharField(max_length=45, null=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cattle')),
            ],
            options={
                'db_table': 'cattle_pregnancy',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('farm_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='erp.farmentity')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('marital_status', models.CharField(max_length=20, null=True)),
                ('person_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.persontitle')),
                ('person_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.persontype')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('farm_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='erp.farmentity')),
                ('supplier_name', models.CharField(max_length=250, null=True)),
                ('account_number', models.CharField(max_length=45, null=True)),
                ('supplier_type_id', models.IntegerField()),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='FarmEntityContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=100)),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.contacttype')),
                ('farm_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.farmentity')),
            ],
            options={
                'db_table': 'farm_entity_contact',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=45, null=True)),
                ('unit_price', models.CharField(max_length=45, null=True)),
                ('measurement', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=45, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.item')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='MilkProduction',
            fields=[
                ('milk_production_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_in_liter', models.FloatField(null=True)),
                ('milk_time', models.DateTimeField(null=True)),
                ('fat_content', models.FloatField(null=True)),
                ('protein_content', models.FloatField(null=True)),
                ('somatic_cell_count', models.FloatField(null=True)),
                ('duration_in_min', models.FloatField(null=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cattle')),
            ],
            options={
                'db_table': 'milk_production',
            },
        ),
        migrations.CreateModel(
            name='OrderHasItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45, null=True)),
                ('quantity', models.CharField(max_length=45, null=True)),
                ('measurement', models.CharField(max_length=45, null=True)),
                ('extra_charges', models.FloatField(null=True)),
                ('extracharge_reasons', models.CharField(max_length=150, null=True)),
                ('taxes_in_percent', models.FloatField(null=True)),
                ('discount', models.FloatField(null=True)),
                ('modified_date', models.CharField(max_length=45, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.order')),
            ],
            options={
                'db_table': 'order_has_item',
            },
        ),
        migrations.CreateModel(
            name='FarmEntityAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100, null=True)),
                ('zone_subcity', models.CharField(max_length=100, null=True)),
                ('woreda', models.CharField(max_length=100, null=True)),
                ('kebele', models.CharField(max_length=45, null=True)),
                ('house_number', models.CharField(max_length=45, null=True)),
                ('street_name', models.CharField(max_length=250, null=True)),
                ('farm_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.farmentity')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.region')),
            ],
            options={
                'db_table': 'farm_entity_address',
            },
        ),
        migrations.CreateModel(
            name='CattleHasVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cattle_given_time', models.DateField(null=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cattle')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.vaccine')),
            ],
            options={
                'db_table': 'cattle_has_vaccine',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_farm_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='erp.person')),
                ('salary', models.FloatField(null=True)),
                ('hire_date', models.DateField(null=True)),
                ('national_id', models.CharField(max_length=100, null=True)),
                ('available_leave_hours', models.FloatField(null=True)),
                ('status', models.SmallIntegerField(null=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('contract_type', models.CharField(max_length=30, null=True)),
                ('contract_period_in_month', models.IntegerField(null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.department')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.job')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='OrderHasItemSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('quantity', models.CharField(max_length=45, null=True)),
                ('status', models.CharField(max_length=45, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.orderhasitem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.supplier')),
            ],
            options={
                'db_table': 'order_has_item_supplier',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='inventory_approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_approved_orders', to='erp.employee'),
        ),
        migrations.AddField(
            model_name='order',
            name='purchase_approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_approved_orders', to='erp.employee'),
        ),
        migrations.AddField(
            model_name='order',
            name='request_approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_approved_orders', to='erp.employee'),
        ),
        migrations.AddField(
            model_name='order',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_orders', to='erp.employee'),
        ),
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('guarantee_id', models.AutoField(primary_key=True, serialize=False)),
                ('salary_evaluation', models.FloatField(null=True)),
                ('guarantee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.guaranteetype')),
                ('person_farm_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employee')),
            ],
            options={
                'db_table': 'guarantee',
            },
        ),
        migrations.CreateModel(
            name='FeedTime',
            fields=[
                ('feed_time_id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_time', models.DateTimeField(null=True)),
                ('feed_time_status', models.CharField(max_length=45, null=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cattle')),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.feedformulation')),
                ('feed_time_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.feedtimecategory')),
                ('person_farm_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employee')),
            ],
            options={
                'db_table': 'feed_time',
            },
        ),
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('salary', models.FloatField(null=True)),
                ('person_farm_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employee')),
            ],
            options={
                'db_table': 'employee_experience',
            },
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('salary', models.FloatField(null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.department')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.job')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employee')),
            ],
            options={
                'db_table': 'job_history',
                'unique_together': {('department', 'job', 'employee')},
            },
        ),
    ]
