# Generated by Django 5.0.4 on 2024-05-01 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CattleBreed',
            fields=[
                ('cattle_breed_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cattle_breed_name', models.CharField(max_length=100, null=True)),
                ('cattle_breed_description', models.CharField(max_length=200, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'cattle_breed',
            },
        ),
        migrations.CreateModel(
            name='CattleStatus',
            fields=[
                ('cattle_status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cattle_status', models.CharField(max_length=100, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'cattle_status',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='FeedFormulation',
            fields=[
                ('feed_formulation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('feed_formulation_descriprion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'feed_formulation',
            },
        ),
        migrations.CreateModel(
            name='FeedTimeCategory',
            fields=[
                ('feed_time_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('feed_time_category', models.CharField(max_length=200, null=True)),
                ('start_time', models.CharField(max_length=45, null=True)),
                ('end_time', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'feed_time_category',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=45)),
                ('job_min_salary', models.FloatField(null=True)),
                ('job_max_salary', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('vaccine_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=45, null=True)),
                ('vaccine_benefit', models.CharField(max_length=2555, null=True)),
                ('vaccine_recommended_time', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'vaccine',
            },
        ),
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('cattle_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cattle_date_of_birth', models.DateTimeField(null=True)),
                ('cattle_name', models.CharField(max_length=50, null=True)),
                ('cattle_gender', models.CharField(max_length=15, null=True)),
                ('cattle_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cattlebreed')),
                ('cattle_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cattlestatus')),
            ],
            options={
                'db_table': 'cattle',
            },
        ),
        migrations.CreateModel(
            name='CattlePhoto',
            fields=[
                ('cattle_photo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cattle_photo_url', models.CharField(max_length=200, null=True)),
                ('cattle_photo_description', models.CharField(max_length=200, null=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cattle')),
            ],
            options={
                'db_table': 'cattle_photo',
            },
        ),
        migrations.CreateModel(
            name='CattlePregnancy',
            fields=[
                ('cattle_pregnancy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cattle_pregnancy_type', models.CharField(max_length=45, null=True)),
                ('cattle_pregnancy_date', models.DateField()),
                ('cattle_expected_delivery_date', models.DateField(null=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cattle')),
            ],
            options={
                'db_table': 'cattle_pregnancy',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_farm_entity_id', models.IntegerField(primary_key=True, serialize=False)),
                ('salary', models.FloatField(null=True)),
                ('hire_date', models.DateField(null=True)),
                ('national_id', models.CharField(max_length=100, null=True)),
                ('availableleavehours', models.FloatField(null=True)),
                ('status', models.SmallIntegerField(null=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.department')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.job')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='FeedTime',
            fields=[
                ('feed_time_id', models.IntegerField(primary_key=True, serialize=False)),
                ('feed_time', models.DateTimeField(null=True)),
                ('feed_time_status', models.CharField(max_length=45, null=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cattle')),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.feedformulation')),
                ('person_farm_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employee')),
                ('feed_time_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.feedtimecategory')),
            ],
            options={
                'db_table': 'feed_time',
            },
        ),
        migrations.CreateModel(
            name='MilkProduction',
            fields=[
                ('milk_production_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount_in_liter', models.FloatField(null=True)),
                ('milk_time', models.DateTimeField(null=True)),
                ('fat_content', models.FloatField(null=True)),
                ('protein_content', models.FloatField(null=True)),
                ('somatic_cell_count', models.FloatField(null=True)),
                ('duration_in_min', models.FloatField(null=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cattle')),
            ],
            options={
                'db_table': 'milk_production',
            },
        ),
        migrations.CreateModel(
            name='CattleHasVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cattle_given_time', models.DateField(null=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cattle')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.vaccine')),
            ],
            options={
                'db_table': 'cattle_has_vaccine',
            },
        ),
    ]
