# Generated by Django 5.0.4 on 2024-05-22 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattlehealthcheckup',
            name='checked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.person'),
        ),
        migrations.AlterField(
            model_name='cattlepregnancy',
            name='check_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.person'),
        ),
        migrations.AlterField(
            model_name='cattlepregnancy',
            name='data_encoded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.employee'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
