# Generated by Django 5.0.4 on 2024-06-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleType',
        ),
        migrations.AddField(
            model_name='cattle',
            name='vaccines',
            field=models.ManyToManyField(related_name='cattle', through='erp.CattleHasVaccine', to='erp.vaccine'),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', through='erp.OrderHasItem', to='erp.item'),
        ),
    ]
