# Generated by Django 5.0.4 on 2024-05-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='estimated_price',
            field=models.FloatField(null=True),
        ),
    ]
