# Generated by Django 5.0.4 on 2024-05-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='approval_status',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
