# Generated by Django 5.0.4 on 2024-05-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_stock_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhasitemsupplier',
            name='inventory_status',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
