# Generated by Django 5.0.4 on 2024-05-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_cattlehealthcheckup_checked_by_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
    ]
