# Generated by Django 5.0.4 on 2024-06-04 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_task_rename_shift_id_shift_id_shift_modified_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedtime',
            name='cattle',
        ),
        migrations.RemoveField(
            model_name='feedtime',
            name='feed_time_category',
        ),
        migrations.RemoveField(
            model_name='feedtime',
            name='formulation',
        ),
        migrations.RemoveField(
            model_name='feedtime',
            name='person_farm_entity',
        ),
        migrations.RenameField(
            model_name='feedformulation',
            old_name='feed_formulation_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='feedformulation',
            name='feed_formulation_description',
        ),
        migrations.AddField(
            model_name='feedformulation',
            name='end_age_in_weeks',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='feedformulation',
            name='modified_date',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='feedformulation',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedformulation',
            name='start_age_in_weeks',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='orderhasitemsupplier',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_items', to='erp.orderhasitem'),
        ),
        migrations.CreateModel(
            name='CattleHasFeed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_time', models.DateTimeField(null=True)),
                ('consumption_status', models.CharField(max_length=45, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('cattle_farm_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cattle')),
                ('feed_formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.feedformulation')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.shift')),
            ],
            options={
                'db_table': 'cattle_has_feed',
            },
        ),
        migrations.CreateModel(
            name='FeedIngredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(null=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('feed_formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.feedformulation')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.item')),
                ('item_measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.itemmeasurement')),
            ],
            options={
                'db_table': 'feed_ingredient',
            },
        ),
        migrations.DeleteModel(
            name='FeedTimeCategory',
        ),
        migrations.DeleteModel(
            name='FeedTime',
        ),
    ]
