# Generated by Django 5.0.4 on 2024-06-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_delete_saletype_cattle_vaccines_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='directlyaddeditem',
            name='added_date',
            field=models.DateTimeField(null=True),
        ),
    ]
