# Generated by Django 5.0.4 on 2024-06-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_paymentmethod_customer_salesorder_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='person_farm_entity_id',
            new_name='person_farm_entity',
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
