# Generated by Django 5.0.4 on 2024-05-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_cattle_estimated_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattlephoto',
            name='cattle_photo_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
