# Generated by Django 5.0.4 on 2024-05-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_cattlephoto_cattle_photo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_type', models.CharField(max_length=255, null=True)),
                ('contact_type_desc', models.CharField(max_length=255, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'contact_type',
            },
        ),
        migrations.CreateModel(
            name='GuaranteeType',
            fields=[
                ('guarantee_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('guarantee_type', models.CharField(max_length=100, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'guarantee_type',
            },
        ),
        migrations.CreateModel(
            name='PersonTitle',
            fields=[
                ('person_title_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_title', models.CharField(max_length=45, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'person_title',
            },
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('person_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_type', models.CharField(max_length=100, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'person_type',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='SaleType',
            fields=[
                ('sale_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_type', models.CharField(max_length=100, null=True)),
                ('modified_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'sale_type',
            },
        ),
        migrations.CreateModel(
            name='SupplierType',
            fields=[
                ('supplier_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_type', models.CharField(max_length=100, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'supplier_type',
            },
        ),
    ]
