# Generated by Django 5.0.4 on 2024-05-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_orderhasitemsupplier_inventory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='directlyaddeditem',
            name='quantity',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
