# Generated by Django 5.0.4 on 2024-06-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_directlyaddeditem_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='logo_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
