# Generated by Django 5.0.4 on 2024-05-22 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_userprofile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.employee'),
        ),
    ]
