# Generated by Django 5.0.4 on 2024-06-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_stockout_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingredient',
            name='quantity',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
