# Generated by Django 5.0.4 on 2024-05-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_contacttype_guaranteetype_persontitle_persontype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattlebreed',
            name='cattle_breed_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cattlepregnancy',
            name='cattle_pregnancy_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cattlestatus',
            name='cattle_status_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='person_farm_entity_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedformulation',
            name='feed_formulation_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedtime',
            name='feed_time_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedtimecategory',
            name='feed_time_category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='milkproduction',
            name='milk_production_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
