# Generated by Django 5.0.4 on 2024-05-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_userprofile_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMeasurement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('measurement', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item_measurement',
            },
        ),
    ]
