# Generated by Django 5.0.4 on 2024-05-30 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_directlyaddeditem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockout',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockout_requests', to='erp.employee'),
        ),
    ]
