# Generated by Django 5.0.4 on 2024-06-11 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_feedingredient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.paymentmethod'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_status',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
