# Generated by Django 5.0.4 on 2024-05-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_stockout_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='item_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
