# Generated by Django 5.0.4 on 2024-05-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_cattlebreed_cattle_breed_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cattlebreed',
            old_name='cattle_breed_name',
            new_name='cattle_breed_type',
        ),
    ]
