# Generated by Django 5.0.4 on 2024-05-27 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_itemmeasurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=45)),
                ('unit_price', models.CharField(max_length=45, null=True)),
                ('type', models.CharField(max_length=45, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.item')),
                ('item_measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.itemmeasurement')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.order')),
            ],
            options={
                'db_table': 'item_inventory',
            },
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
