# Generated by Django 5.0.4 on 2024-06-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_salesorder_payment_method_salesorder_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='approval_status',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
