# Generated by Django 5.0.4 on 2024-05-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_rename_cattle_breed_name_cattlebreed_cattle_breed_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattlepregnancy',
            name='cattle_pregnancy_status',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
