# Generated by Django 5.0.4 on 2024-05-27 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_iteminventory_delete_inventory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobhistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='person_farm_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.employee'),
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='promotion_or_demotion',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.department'),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.job'),
        ),
        migrations.RemoveField(
            model_name='jobhistory',
            name='employee',
        ),
    ]
