# Generated by Django 5.0.4 on 2024-06-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_salesorder_item_measurement_salesorder_item_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentMilkPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_price', models.FloatField()),
            ],
            options={
                'db_table': 'current_milk_price',
            },
        ),
    ]
