# Generated by Django 5.0.4 on 2024-05-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_cattlepregnancy_cattle_pregnancy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='vaccine_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
