# Generated by Django 5.0.4 on 2024-06-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_taskassignment_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
