# Generated by Django 5.0.4 on 2024-06-12 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_taskassignment_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=300, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=45, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'farm',
            },
        ),
        migrations.CreateModel(
            name='FarmAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100, null=True)),
                ('zone_subcity', models.CharField(max_length=100, null=True)),
                ('woreda', models.CharField(max_length=100, null=True)),
                ('kebele', models.CharField(max_length=45, null=True)),
                ('house_number', models.CharField(max_length=45, null=True)),
                ('street_name', models.CharField(max_length=250, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.farm')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.region')),
            ],
            options={
                'db_table': 'farm_address',
            },
        ),
        migrations.CreateModel(
            name='FarmContacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=100)),
                ('contact_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.contacttype')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.farm')),
            ],
            options={
                'db_table': 'farm_contacts',
            },
        ),
    ]
