# Generated by Django 5.0.4 on 2024-05-27 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_employeeleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleave',
            name='person_farm_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='erp.employee'),
        ),
    ]
