# Generated by Django 5.0.4 on 2024-05-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_alter_vaccine_vaccine_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_name', models.CharField(max_length=45, null=True)),
                ('shift_start_time', models.DateTimeField(null=True)),
                ('shift_end_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'shift',
            },
        ),
    ]
