# Generated by Django 5.0.4 on 2024-06-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_currentmilkprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cattlepregnancy',
            name='check_by',
        ),
        migrations.AddField(
            model_name='cattlepregnancy',
            name='checked_by',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cattlehealthcheckup',
            name='checked_by',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
