# Generated by Django 5.0.4 on 2024-05-28 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_alter_employeeleave_person_farm_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhasitem',
            name='measurement',
        ),
        migrations.AddField(
            model_name='orderhasitem',
            name='item_measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.itemmeasurement'),
        ),
    ]
