# Generated by Django 5.0.4 on 2024-06-13 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_farm_country_farm_house_number_farm_kebele_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='acquired_status',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_cattle', to='erp.cattle'),
        ),
        migrations.AddField(
            model_name='cattle',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_cattle', to='erp.cattle'),
        ),
    ]
