# Generated by Django 5.0.4 on 2024-05-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_rename_feed_formulation_descriprion_feedformulation_feed_formulation_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
