# Generated by Django 5.0.4 on 2024-07-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_alter_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattlehasvaccine',
            name='given_status',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='cattlehasvaccine',
            name='modified_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_pic_path',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='feedformulation',
            name='end_age_in_weeks',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='feedformulation',
            name='start_age_in_weeks',
            field=models.FloatField(null=True),
        ),
    ]
