# Generated by Django 5.0.4 on 2024-08-05 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_cattlehasvaccine_given_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_type_id',
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.suppliertype'),
        ),
    ]
