# Generated by Django 5.0.4 on 2024-05-07 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_date', models.DateField(null=True)),
                ('request_approved', models.CharField(max_length=10, null=True)),
                ('request_approved_date', models.DateTimeField(null=True)),
                ('purchase_approved', models.CharField(max_length=10, null=True)),
                ('purchase_approved_date', models.DateTimeField(null=True)),
                ('inventory_approved', models.CharField(max_length=10, null=True)),
                ('inventory_approved_date', models.DateTimeField(null=True)),
                ('inventory_approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_approved_orders', to='erp.employee')),
                ('purchase_approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_approved_orders', to='erp.employee')),
                ('request_approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_approved_orders', to='erp.employee')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_orders', to='erp.employee')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderHasItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45, null=True)),
                ('quantity', models.CharField(max_length=45, null=True)),
                ('measurement', models.CharField(max_length=45, null=True)),
                ('modified_date', models.CharField(max_length=45, null=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.item')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.order')),
            ],
            options={
                'db_table': 'order_has_item',
            },
        ),
    ]
