# Generated by Django 5.0.4 on 2024-06-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_cattle_acquired_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='total_price',
            field=models.FloatField(null=True),
        ),
    ]
