# Generated by Django 5.0.4 on 2024-08-06 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_remove_supplier_supplier_type_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CattleSales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(null=True)),
                ('quantity', models.FloatField()),
                ('unit_price', models.FloatField(null=True)),
                ('payment_status', models.CharField(max_length=45, null=True)),
                ('total_amount', models.FloatField(null=True)),
                ('cattle_farm_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cattle')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.customer')),
                ('payment_method', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.paymentmethod')),
            ],
        ),
    ]
