# Generated by Django 5.0.4 on 2024-05-07 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_rename_item_id_orderhasitem_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_orders', to='erp.employee'),
        ),
    ]
