# Generated by Django 5.0.4 on 2024-08-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_cattlesales'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cattlesales',
            table='cattle_sales',
        ),
    ]
