# Generated by Django 5.0.4 on 2024-05-08 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_alter_order_requested_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmEntity',
            fields=[
                ('farm_entity_id', models.AutoField(primary_key=True, serialize=False)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'farm_entity',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('farm_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='erp.farmentity')),
                ('supplier_name', models.CharField(max_length=250, null=True)),
                ('account_number', models.CharField(max_length=45, null=True)),
                ('supplier_type_id', models.IntegerField()),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
    ]
