# Generated by Django 5.0.4 on 2024-06-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_rename_total_price_stock_current_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherIncomeExpense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(null=True)),
                ('amount', models.FloatField()),
                ('transaction_type', models.CharField(max_length=45)),
                ('transaction_status', models.CharField(max_length=45)),
                ('reason', models.CharField(max_length=200, null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
