# Generated by Django 5.0.4 on 2024-08-06 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_remove_cattlesales_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattlesales',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.paymentmethod'),
        ),
    ]
