# Generated by Django 5.0.4 on 2024-05-08 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_farmentity_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHasItemSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.orderhasitem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.supplier')),
            ],
            options={
                'db_table': 'order_has_item_supplier',
            },
        ),
    ]
