# Generated by Django 5.0.4 on 2024-06-19 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_otherincomeexpense'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='otherincomeexpense',
            table='other_income_expense',
        ),
    ]
