# Generated by Django 5.0.4 on 2024-08-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_alter_cattlesales_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_approval_status',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='reason',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='task_updated_time',
            field=models.DateTimeField(null=True),
        ),
    ]
