# Generated by Django 5.0.4 on 2024-06-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_alter_otherincomeexpense_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='order_date',
            field=models.DateTimeField(null=True),
        ),
    ]
