# Generated by Django 5.0.4 on 2024-08-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_employee_employment_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_leave_update',
            field=models.DateField(null=True),
        ),
    ]
