# Generated by Django 5.0.4 on 2024-08-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_employee_last_leave_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='years_of_experience',
            field=models.FloatField(default=0, null=True),
        ),
    ]
