# Generated by Django 5.0.4 on 2024-05-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_purchaseorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
