# Generated by Django 5.0.4 on 2024-08-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_employee_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_year',
            field=models.IntegerField(null=True),
        ),
    ]
