# Generated by Django 5.0.4 on 2024-05-09 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_delete_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='orderhasitem',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orderhasitem',
            name='extra_charges',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orderhasitem',
            name='extracharge_reasons',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='orderhasitem',
            name='taxes_in_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orderhasitemsupplier',
            name='status',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='inventory_approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_approved_orders', to='erp.employee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_approved_orders', to='erp.employee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='request_approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_approved_orders', to='erp.employee'),
        ),
    ]
