# Generated by Django 5.0.4 on 2024-05-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_order_status_orderhasitem_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='item_id',
            new_name='item',
        ),
    ]
