# Generated by Django 5.0.4 on 2024-05-12 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_rename_item_id_inventory_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='availableleavehours',
            new_name='available_leave_hours',
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_period_in_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='FarmEntityAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, null=True)),
                ('zone_subcity', models.CharField(max_length=100, null=True)),
                ('woreda', models.CharField(max_length=100, null=True)),
                ('kebele', models.CharField(max_length=45, null=True)),
                ('house_number', models.CharField(max_length=45, null=True)),
                ('street_name', models.CharField(max_length=250, null=True)),
                ('farm_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.farmentity')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.region')),
            ],
            options={
                'db_table': 'farm_entity_address',
            },
        ),
        migrations.CreateModel(
            name='FarmEntityContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=100)),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.contacttype')),
                ('farm_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.farmentity')),
            ],
            options={
                'db_table': 'farm_entity_contact',
            },
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('salary', models.FloatField(null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.job')),
            ],
            options={
                'db_table': 'job_history',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('marital_status', models.CharField(max_length=20, null=True)),
                ('farm_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='erp.farmentity')),
                ('person_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.persontitle')),
                ('person_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.persontype')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='person_farm_entity_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='erp.person'),
        ),
    ]
