# Generated by Django 5.0.4 on 2024-08-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_employee_original_hire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='leave_year',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='original_hire_date',
        ),
    ]
