# Generated by Django 5.0.4 on 2024-05-12 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_rename_availableleavehours_employee_available_leave_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='person_farm_entity_id',
            new_name='person_farm_entity',
        ),
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='farm_entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='erp.farmentity'),
        ),
    ]
