# Generated by Django 5.0.4 on 2024-05-12 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_rename_person_farm_entity_id_employee_person_farm_entity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmentitycontact',
            name='id',
        ),
        migrations.AlterField(
            model_name='farmentitycontact',
            name='farm_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='erp.farmentity'),
        ),
    ]
