# Generated by Django 5.0.4 on 2024-05-12 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_remove_farmentityaddress_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmentityaddress',
            name='farm_entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='erp.farmentity'),
        ),
        migrations.AlterField(
            model_name='farmentitycontact',
            name='farm_entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='erp.farmentity'),
        ),
    ]
