# Generated by Django 5.0.4 on 2024-05-12 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_alter_farmentityaddress_farm_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmentityaddress',
            name='farm_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='erp.farmentity'),
        ),
        migrations.AlterField(
            model_name='farmentitycontact',
            name='farm_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='erp.farmentity'),
        ),
        migrations.AlterUniqueTogether(
            name='jobhistory',
            unique_together={('department', 'job', 'employee')},
        ),
    ]
