# Generated by Django 5.0.4 on 2024-05-13 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0027_alter_farmentityaddress_farm_entity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('salary', models.FloatField(null=True)),
                ('person_farm_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employee')),
            ],
            options={
                'db_table': 'employee_experience',
            },
        ),
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('guarantee_id', models.AutoField(primary_key=True, serialize=False)),
                ('salary_evaluation', models.FloatField(null=True)),
                ('employee_farm_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.employee')),
                ('guarantee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.guaranteetype')),
            ],
            options={
                'db_table': 'guarantee',
            },
        ),
    ]
