# Generated by Django 5.0.4 on 2024-05-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_employeeexperience_guarantee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guarantee',
            old_name='employee_farm_entity',
            new_name='person_farm_entity',
        ),
    ]
