# Generated by Django 5.0.4 on 2024-05-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0029_rename_employee_farm_entity_guarantee_person_farm_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhasitemsupplier',
            name='quantity',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
